//! Generates `subgraph.yaml` from Redstart `source`/`template`/`handler`
//! declarations.
//!
//! Because handlers bind to ABI events *by reference* (`handler on Src.Event`),
//! the manifest's `eventHandlers` list is derived, not hand-maintained — the
//! string-typed coupling that causes manifest/handler drift today is gone.

use crate::names::Names;
use redstart_checker::AbiIndex;
use redstart_parser::ast::{
    BlockFilter, Expr, GraftDecl, HandlerDecl, HandlerKind, Setting, SourceDecl, TemplateDecl,
};
use std::collections::BTreeSet;

/// The spec version emitted. Redstart owns this so the developer never touches
/// the `specVersion`/`apiVersion` compatibility matrix. Timeseries/aggregations
/// require ≥ 1.1.0; everything else here is fine at 1.0.0.
const SPEC_VERSION: &str = "1.0.0";
const SPEC_VERSION_AGGREGATIONS: &str = "1.1.0";
const API_VERSION: &str = "0.0.9";

/// Inputs for manifest generation.
pub struct ManifestInput<'a> {
    /// The subgraph name/description.
    pub name: &'a str,
    /// Optional description.
    pub description: Option<&'a str>,
    /// All data sources.
    pub sources: &'a [&'a SourceDecl],
    /// All templates.
    pub templates: &'a [&'a TemplateDecl],
    /// All handlers.
    pub handlers: &'a [&'a HandlerDecl],
    /// All entity names (declared in the schema).
    pub entity_names: &'a [String],
    /// Whether the schema uses timeseries entities or aggregations (→ ≥ 1.1.0).
    pub uses_aggregations: bool,
    /// Project-wide export names (source-qualified where they would collide).
    pub names: &'a Names,
    /// ABIs reached only through `Abi.bind(addr)`. `graph codegen` emits one
    /// contract class per ABI listed on a data source, so these must be listed
    /// alongside each source's own ABI or the generated mapping won't compile.
    pub bound_abis: &'a BTreeSet<String>,
    /// `graft { base, block }`, if the project declares one.
    pub graft: Option<&'a GraftDecl>,
}

/// Render `subgraph.yaml`, collecting any warnings (e.g. unresolved signatures).
#[must_use]
pub fn render(input: &ManifestInput, abi_index: &mut AbiIndex) -> (String, Vec<String>) {
    let mut out = String::new();
    let mut warnings = Vec::new();

    let spec_version = if input.uses_aggregations {
        SPEC_VERSION_AGGREGATIONS
    } else {
        SPEC_VERSION
    };
    out.push_str("# Generated by Redstart — do not edit by hand.\n");
    out.push_str(&format!("specVersion: {spec_version}\n"));
    if let Some(desc) = input.description {
        // Quoted: a description containing `:` or `#` is otherwise invalid YAML
        // and the graph CLI refuses to parse the manifest at all.
        out.push_str(&format!("description: {}\n", yaml_string(desc)));
    }
    out.push_str(&format!("# subgraph: {}\n", input.name));
    out.push_str("schema:\n  file: ./schema.graphql\n");

    // Default to pruning historical entity versions (§4.5): the graph-node default
    // is `prune: never` (largest DB, slowest queries). `auto` keeps only the
    // history needed for reorgs — smaller DB, faster queries — with no effect on
    // current-state queries.
    out.push_str("indexerHints:\n  prune: auto\n");

    // Grafting is a manifest *feature*, and graph-node rejects a `graft:` block
    // that is not declared in `features:`. Both or neither.
    if let Some(graft) = input.graft {
        let base = setting_str(&graft.settings, "base");
        let block = setting_str(&graft.settings, "block");
        match (base, block) {
            (Some(base), Some(block)) => {
                out.push_str("features:\n  - grafting\n");
                out.push_str(&format!("graft:\n  base: {base}\n  block: {block}\n"));
            }
            _ => warnings
                .push("`graft` needs both `base` and `block`; emitting no graft".to_string()),
        }
    }

    out.push_str("dataSources:\n");
    for source in input.sources {
        render_data_source(&mut out, source, input, abi_index, &mut warnings);
    }

    if !input.templates.is_empty() {
        out.push_str("templates:\n");
        for template in input.templates {
            render_template(&mut out, template, input, abi_index, &mut warnings);
        }
    }

    (out, warnings)
}

fn render_data_source(
    out: &mut String,
    source: &SourceDecl,
    input: &ManifestInput,
    abi_index: &mut AbiIndex,
    warnings: &mut Vec<String>,
) {
    let abi = setting_str(&source.settings, "abi").unwrap_or_else(|| "Contract".to_string());
    let network = setting_str(&source.settings, "network").unwrap_or_else(|| "mainnet".to_string());
    let address = setting_str(&source.settings, "address").unwrap_or_default();
    let start_block =
        setting_str(&source.settings, "startBlock").unwrap_or_else(|| "0".to_string());

    out.push_str(&format!(
        "  - kind: ethereum\n    name: {}\n",
        source.name.name
    ));
    out.push_str(&format!("    network: {network}\n"));
    out.push_str("    source:\n");
    out.push_str(&format!("      address: \"{address}\"\n"));
    out.push_str(&format!("      abi: {abi}\n"));
    out.push_str(&format!("      startBlock: {start_block}\n"));

    render_mapping(out, &source.name.name, &abi, input, abi_index, warnings);
}

fn render_template(
    out: &mut String,
    template: &TemplateDecl,
    input: &ManifestInput,
    abi_index: &mut AbiIndex,
    warnings: &mut Vec<String>,
) {
    if is_file_template(template) {
        render_file_template(out, template, input, warnings);
        return;
    }

    let abi = setting_str(&template.settings, "abi").unwrap_or_else(|| "Contract".to_string());
    let network =
        setting_str(&template.settings, "network").unwrap_or_else(|| "mainnet".to_string());

    out.push_str(&format!(
        "  - kind: ethereum\n    name: {}\n",
        template.name.name
    ));
    out.push_str(&format!("    network: {network}\n"));
    out.push_str("    source:\n");
    out.push_str(&format!("      abi: {abi}\n"));

    render_mapping(out, &template.name.name, &abi, input, abi_index, warnings);
}

/// Whether a template declares `kind: file` (a file/IPFS data source).
fn is_file_template(template: &TemplateDecl) -> bool {
    matches!(
        setting_str(&template.settings, "kind").as_deref(),
        Some("file" | "file/ipfs" | "ipfs")
    )
}

/// Render a `kind: file/ipfs` template — no network/address, a single `handler:`.
fn render_file_template(
    out: &mut String,
    template: &TemplateDecl,
    input: &ManifestInput,
    warnings: &mut Vec<String>,
) {
    out.push_str(&format!(
        "  - kind: file/ipfs\n    name: {}\n",
        template.name.name
    ));
    out.push_str("    mapping:\n      kind: file/ipfs\n");
    out.push_str(&format!("      apiVersion: {API_VERSION}\n"));
    out.push_str("      language: wasm/assemblyscript\n");

    out.push_str("      entities:\n");
    for name in input.entity_names {
        out.push_str(&format!("        - {name}\n"));
    }
    out.push_str("      abis: []\n");

    let file_handlers: Vec<&&HandlerDecl> = input
        .handlers
        .iter()
        .filter(|h| h.is_file() && h.source.name == template.name.name)
        .collect();
    match file_handlers.as_slice() {
        [handler] => out.push_str(&format!(
            "      handler: {}\n",
            input.names.fn_name(handler)
        )),
        [] => warnings.push(format!(
            "file template `{}` has no `handler file {0}(content) {{ … }}`",
            template.name.name
        )),
        many => warnings.push(format!(
            "file template `{}` has {} file handlers; file/ipfs allows exactly one",
            template.name.name,
            many.len()
        )),
    }

    out.push_str("      file: ./src/mappings.ts\n");
}

fn render_mapping(
    out: &mut String,
    source_name: &str,
    abi: &str,
    input: &ManifestInput,
    abi_index: &mut AbiIndex,
    warnings: &mut Vec<String>,
) {
    out.push_str("    mapping:\n      kind: ethereum/events\n");
    out.push_str(&format!("      apiVersion: {API_VERSION}\n"));
    out.push_str("      language: wasm/assemblyscript\n");

    out.push_str("      entities:\n");
    for name in input.entity_names {
        out.push_str(&format!("        - {name}\n"));
    }

    out.push_str("      abis:\n");
    // ABIs are copied into the build dir, so the manifest references them
    // locally. The source's own ABI comes first; every ABI the project binds for
    // a contract read follows, because `graph codegen` only emits a contract
    // class for an ABI a data source lists — a bound-but-unlisted ABI compiles
    // to `Cannot find name`.
    for name in std::iter::once(abi).chain(
        input
            .bound_abis
            .iter()
            .map(String::as_str)
            .filter(|b| *b != abi),
    ) {
        out.push_str(&format!(
            "        - name: {name}\n          file: ./abis/{name}.json\n"
        ));
    }

    let mine: Vec<&&HandlerDecl> = input
        .handlers
        .iter()
        .filter(|h| h.source.name == source_name)
        .collect();

    // eventHandlers
    let events: Vec<&&HandlerDecl> = mine
        .iter()
        .filter(|h| h.kind == HandlerKind::Event)
        .copied()
        .collect();
    if !events.is_empty() {
        out.push_str("      eventHandlers:\n");
        for handler in events {
            let signature = abi_index
                .event_signature(abi, &handler.event.name)
                .unwrap_or_else(|| {
                    warnings.push(format!(
                        "could not resolve signature for event `{}` in ABI `{abi}`; \
                         emitted a placeholder",
                        handler.event.name
                    ));
                    format!("{}(/* TODO: resolve from ABI */)", handler.event.name)
                });
            out.push_str(&format!(
                "        - event: {signature}\n          handler: {}\n",
                input.names.fn_name(handler)
            ));
        }
    }

    // callHandlers
    let calls: Vec<&&HandlerDecl> = mine
        .iter()
        .filter(|h| h.kind == HandlerKind::Call)
        .copied()
        .collect();
    if !calls.is_empty() {
        out.push_str("      callHandlers:\n");
        for handler in calls {
            let signature = abi_index
                .function_signature(abi, &handler.event.name)
                .unwrap_or_else(|| {
                    warnings.push(format!(
                        "could not resolve signature for function `{}` in ABI `{abi}`; \
                         emitted a placeholder",
                        handler.event.name
                    ));
                    format!("{}(/* TODO: resolve from ABI */)", handler.event.name)
                });
            out.push_str(&format!(
                "        - function: {signature}\n          handler: {}\n",
                input.names.fn_name(handler)
            ));
        }
    }

    // blockHandlers
    let blocks: Vec<&&HandlerDecl> = mine
        .iter()
        .filter(|h| matches!(h.kind, HandlerKind::Block(_)))
        .copied()
        .collect();
    if !blocks.is_empty() {
        out.push_str("      blockHandlers:\n");
        for handler in blocks {
            out.push_str(&format!(
                "        - handler: {}\n",
                input.names.fn_name(handler)
            ));
            match &handler.kind {
                HandlerKind::Block(BlockFilter::Polling(every)) => {
                    out.push_str(&format!(
                        "          filter:\n            kind: polling\n            every: {every}\n"
                    ));
                }
                HandlerKind::Block(BlockFilter::Once) => {
                    out.push_str("          filter:\n            kind: once\n");
                }
                _ => {}
            }
        }
    }

    out.push_str("      file: ./src/mappings.ts\n");
}

/// Render a string as a double-quoted YAML scalar, escaping what YAML requires.
fn yaml_string(s: &str) -> String {
    let escaped = s.replace('\\', "\\\\").replace('"', "\\\"");
    format!("\"{escaped}\"")
}

/// Render a setting value to a manifest string.
fn setting_str(settings: &[Setting], key: &str) -> Option<String> {
    let setting = settings.iter().find(|s| s.key.name == key)?;
    Some(render_value(&setting.value))
}

fn render_value(expr: &Expr) -> String {
    match expr {
        Expr::Path { segments, .. } => segments
            .iter()
            .map(|s| s.name.clone())
            .collect::<Vec<_>>()
            .join("::"),
        Expr::Hex { raw, .. } | Expr::Int { raw, .. } | Expr::Decimal { raw, .. } => raw.clone(),
        Expr::Str { value, .. } => value.clone(),
        Expr::Bool { value, .. } => value.to_string(),
        _ => String::new(),
    }
}
