//! Generates `schema.graphql` from Redstart `entity` declarations.
//!
//! The whole point of unification: these entity types are the *same* source of
//! truth the handlers are checked against, so the schema can never drift from
//! the mappings.

use redstart_parser::ast::{
    AggregationDecl, EntityDecl, EnumDecl, FieldDecl, InterfaceDecl, TypeExpr,
};
use std::collections::HashSet;

/// Render the full GraphQL schema from every declaration kind.
#[must_use]
pub fn render(
    entities: &[&EntityDecl],
    enums: &[&EnumDecl],
    interfaces: &[&InterfaceDecl],
    aggregations: &[&AggregationDecl],
    immutable_inferred: &HashSet<String>,
) -> String {
    let mut out = String::new();
    out.push_str("# Generated by Redstart — do not edit by hand.\n");
    out.push_str("# Source of truth: your .red entity declarations.\n\n");

    for e in enums {
        render_enum(&mut out, e);
        out.push('\n');
    }
    for i in interfaces {
        render_interface(&mut out, i);
        out.push('\n');
    }
    for entity in entities {
        render_entity(&mut out, entity, immutable_inferred);
        out.push('\n');
    }
    for agg in aggregations {
        render_aggregation(&mut out, agg);
        out.push('\n');
    }
    out
}

/// Render an `@aggregation` type — a rollup over a timeseries source.
fn render_aggregation(out: &mut String, agg: &AggregationDecl) {
    let intervals = agg
        .intervals
        .iter()
        .map(|i| format!("\"{}\"", i.name))
        .collect::<Vec<_>>()
        .join(", ");
    out.push_str(&format!(
        "type {} @aggregation(intervals: [{intervals}], source: \"{}\") {{\n",
        agg.name.name, agg.source.name
    ));
    // Aggregations carry the same auto-managed id/timestamp as their source.
    out.push_str("  id: Int8!\n");
    out.push_str("  timestamp: Timestamp!\n");
    for f in &agg.fields {
        let (ty, nonnull) = graphql_type(&f.ty);
        let bang = if nonnull { "!" } else { "" };
        let arg = f
            .arg
            .as_ref()
            .map(|a| format!(", arg: \"{}\"", a.name))
            .unwrap_or_default();
        out.push_str(&format!(
            "  {}: {ty}{bang} @aggregate(fn: \"{}\"{arg})\n",
            f.name.name, f.func.name
        ));
    }
    out.push_str("}\n");
}

fn render_interface(out: &mut String, i: &InterfaceDecl) {
    out.push_str(&format!("interface {} {{\n", i.name.name));
    for field in &i.fields {
        out.push_str(&format!("  {}\n", render_field(field)));
    }
    out.push_str("}\n");
}

fn render_enum(out: &mut String, e: &EnumDecl) {
    out.push_str(&format!("enum {} {{\n", e.name.name));
    for v in &e.variants {
        out.push_str(&format!("  {}\n", v.name));
    }
    out.push_str("}\n");
}

fn render_entity(out: &mut String, entity: &EntityDecl, immutable_inferred: &HashSet<String>) {
    let directives = entity_directives(entity, immutable_inferred);
    let implements = if entity.implements.is_empty() {
        String::new()
    } else {
        let names: Vec<&str> = entity.implements.iter().map(|i| i.name.as_str()).collect();
        format!(" implements {}", names.join(" & "))
    };
    out.push_str(&format!(
        "type {}{implements} {directives} {{\n",
        entity.name.name
    ));
    // A timeseries entity has an auto-incrementing `id: Int8!` and an
    // auto-populated `timestamp: Timestamp!`; inject any the author omitted.
    if entity.modifiers.iter().any(|m| m.name == "timeseries") {
        if !entity.fields.iter().any(|f| f.name.name == "id") {
            out.push_str("  id: Int8!\n");
        }
        if !entity.fields.iter().any(|f| f.name.name == "timestamp") {
            out.push_str("  timestamp: Timestamp!\n");
        }
    }
    for field in &entity.fields {
        out.push_str(&format!("  {}\n", render_field(field)));
    }
    out.push_str("}\n");
}

fn entity_directives(entity: &EntityDecl, immutable_inferred: &HashSet<String>) -> String {
    // Modern graph-cli requires an explicit `immutable` argument on `@entity`.
    let timeseries = entity.modifiers.iter().any(|m| m.name == "timeseries");
    // Immutable if: declared `immutable`, a timeseries (append-only), or *inferred*
    // append-only by the checker (created but never loaded/mutated) — the §4.3
    // optimisation. Immutable entities index faster and use far less disk.
    // `mutable` is an explicit opt-out of both the `immutable` modifier and the
    // append-only inference, for schemas that must stay layout-compatible with a
    // graft base. A timeseries is immutable by construction and cannot opt out.
    let opted_out = entity.modifiers.iter().any(|m| m.name == "mutable");
    let immutable = timeseries
        || (!opted_out
            && (entity.modifiers.iter().any(|m| m.name == "immutable")
                || immutable_inferred.contains(&entity.name.name)));

    let mut args = vec![format!("immutable: {immutable}")];
    if timeseries {
        args.push("timeseries: true".to_string());
    }
    format!("@entity({})", args.join(", "))
}

fn render_field(field: &FieldDecl) -> String {
    let (ty, nonnull) = graphql_type(&field.ty);
    let bang = if nonnull { "!" } else { "" };
    let mut rendered = format!("{}: {ty}{bang}", field.name.name);

    if let Some(back) = &field.derived_from {
        rendered.push_str(&format!(" @derivedFrom(field: \"{}\")", back.name));
    }
    rendered
}

/// Map a Redstart type to `(graphql_type, is_non_null)`.
///
/// `Option<T>` makes a field nullable; everything else is non-null by default —
/// which is exactly how the "no `null`" type-system decision should surface in
/// the schema.
fn graphql_type(ty: &TypeExpr) -> (String, bool) {
    match ty {
        TypeExpr::List { elem, .. } => {
            let (inner, inner_nn) = graphql_type(elem);
            let inner_bang = if inner_nn { "!" } else { "" };
            (format!("[{inner}{inner_bang}]"), true)
        }
        TypeExpr::Generic { base, args, .. } => {
            let base_name = base.simple_name().unwrap_or("");
            match base_name {
                // Optionality is expressed by Option<T> — strip the non-null.
                "Option" => {
                    let inner = args.first();
                    inner.map_or_else(
                        || ("String".to_string(), false),
                        |t| {
                            let (name, _) = graphql_type(t);
                            (name, false)
                        },
                    )
                }
                // Id<T> resolves to its inner scalar (e.g. Id<Bytes> -> Bytes!).
                "Id" => args
                    .first()
                    .map_or_else(|| ("ID".to_string(), true), |t| (scalar_or_ref(t), true)),
                // List<T> as an alternative to [T].
                "List" => {
                    let inner = args
                        .first()
                        .map_or_else(|| "String".to_string(), scalar_or_ref);
                    (format!("[{inner}!]"), true)
                }
                _ => (base_name.to_string(), true),
            }
        }
        TypeExpr::Path { .. } => (scalar_or_ref(ty), true),
    }
}

/// Map a simple named type to its GraphQL scalar, or pass through an entity
/// reference name unchanged.
fn scalar_or_ref(ty: &TypeExpr) -> String {
    let name = ty.simple_name().unwrap_or("String");
    match name {
        "BigInt" => "BigInt",
        "BigDecimal" => "BigDecimal",
        "Bytes" => "Bytes",
        // GraphQL has no Address scalar; The Graph models addresses as Bytes.
        "Address" => "Bytes",
        "String" => "String",
        "Bool" | "Boolean" => "Boolean",
        "Int" => "Int",
        "Int8" => "Int8",
        "Timestamp" => "Timestamp",
        "ID" => "ID",
        other => other, // an entity or enum reference
    }
    .to_string()
}

#[cfg(test)]
mod tests {
    use super::*;
    use redstart_parser::{lex, parse};
    use std::sync::Arc;

    fn schema_of(src: &str) -> String {
        let lexed = lex(src).unwrap();
        let (program, errs) = parse(lexed.tokens(), Arc::from(src));
        assert!(errs.is_empty(), "{errs:#?}");
        let refs: Vec<_> = program.entities.iter().collect();
        let enums: Vec<_> = program.enums.iter().collect();
        let interfaces: Vec<_> = program.interfaces.iter().collect();
        let aggs: Vec<_> = program.aggregations.iter().collect();
        // Schema-only unit tests: no whole-program immutable inference.
        render(&refs, &enums, &interfaces, &aggs, &HashSet::new())
    }

    #[test]
    fn renders_scalars_and_nonnull() {
        let s = schema_of("entity Token { id: Id<Bytes> symbol: String supply: BigInt }");
        assert!(s.contains("type Token @entity(immutable: false) {"));
        assert!(s.contains("id: Bytes!"));
        assert!(s.contains("symbol: String!"));
        assert!(s.contains("supply: BigInt!"));
    }

    #[test]
    fn option_makes_field_nullable() {
        let s = schema_of("entity Token { id: Id<Bytes> name: Option<String> }");
        assert!(s.contains("name: String\n") || s.contains("name: String "));
        assert!(!s.contains("name: String!"));
    }

    #[test]
    fn derived_and_list() {
        let s = schema_of("entity Pool { id: Id<Bytes> swaps: [Swap] derived from pool }");
        assert!(s.contains("swaps: [Swap!]! @derivedFrom(field: \"pool\")"));
    }

    #[test]
    fn immutable_modifier() {
        let s = schema_of("entity Swap immutable { id: Id<Bytes> }");
        assert!(s.contains("@entity(immutable: true)"));
    }

    #[test]
    fn renders_timeseries_and_aggregation() {
        let s = schema_of(
            "entity Data timeseries { price: BigDecimal } \
             aggregation Stats over Data every [hour, day] { total: BigDecimal = sum(price) count: Int8 = count() }",
        );
        // Timeseries entity is implicitly immutable with auto id/timestamp.
        assert!(
            s.contains("type Data @entity(immutable: true, timeseries: true) {"),
            "got:\n{s}"
        );
        assert!(
            s.contains("  id: Int8!\n  timestamp: Timestamp!\n  price: BigDecimal!"),
            "got:\n{s}"
        );
        // Aggregation type with @aggregation + @aggregate directives.
        assert!(
            s.contains(
                "type Stats @aggregation(intervals: [\"hour\", \"day\"], source: \"Data\") {"
            ),
            "got:\n{s}"
        );
        assert!(
            s.contains("total: BigDecimal! @aggregate(fn: \"sum\", arg: \"price\")"),
            "got:\n{s}"
        );
        assert!(
            s.contains("count: Int8! @aggregate(fn: \"count\")"),
            "got:\n{s}"
        );
    }

    #[test]
    fn renders_interface_and_implements() {
        let s = schema_of(
            "interface Token { id: Id<Bytes> symbol: String } \
             entity FT implements Token { id: Id<Bytes> symbol: String supply: BigInt }",
        );
        assert!(
            s.contains("interface Token {\n  id: Bytes!\n  symbol: String!\n}"),
            "got:\n{s}"
        );
        assert!(
            s.contains("type FT implements Token @entity(immutable: false) {"),
            "got:\n{s}"
        );
    }

    #[test]
    fn renders_enums_and_timestamp_scalar() {
        let s = schema_of(
            "enum Kind { Mint, Burn } entity Tx { id: Id<Bytes> kind: Kind at: Timestamp }",
        );
        assert!(s.contains("enum Kind {\n  Mint\n  Burn\n}"), "got:\n{s}");
        assert!(s.contains("kind: Kind!"));
        assert!(s.contains("at: Timestamp!"));
    }
}
